In [1]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.29322035 0.77992922 0.62802376]
 [0.40925301 0.91746454 0.38437789]
 [0.28549793 0.51150348 0.88312119]
 [0.57060073 0.7502816  0.5769995 ]
 [0.96963066 0.82787029 0.04621573]
 [0.33236104 0.63732544 0.39241475]
 [0.45546056 0.31864645 0.9563949 ]
 [0.95695763 0.70489126 0.09205053]
 [0.27995474 0.37074695 0.551313  ]
 [0.4551291  0.76748843 0.68817473]]


numpy.flatten()作用:

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 10],[11, 12, 13]])
b = a > 5 #
print(b)
c = b.flatten().nonzero()[0]
print(c)
d = a.flatten()
print(d)



[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
[ 5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8 10 11 12 13]


In [3]:
e = a.flatten()[c]
print(e)



[ 6  7  8 10 11 12 13]


In [4]:
f = e[:, None]
print(f)



[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [5]:
f = e[:, np.newaxis]
print(f)

[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [6]:
f1 = a[:, np.newaxis]
print(f1)


[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8 10]]

 [[11 12 13]]]


In [7]:
g = np.array([f])
print(g)


[[[ 6]
  [ 7]
  [ 8]
  [10]
  [11]
  [12]
  [13]]]


In [8]:
c_mask = np.zeros(10)
c_mask[:5] = 1  # 将前五个数设置为1
np.random.shuffle(c_mask)
print(c_mask)


[0. 1. 0. 1. 1. 0. 1. 0. 0. 1.]


字典的相关用法

In [9]:
student = [('name','xiao meng'), ('number','110')]
print(type(student))
dict_student = dict(student)    # cover list to dict
print(type(dict_student))



<class 'list'>
<class 'dict'>


In [10]:
idx = dict(
    tain = 0,
    val = 0,
    test = 0
)
print(idx)


{'tain': 0, 'val': 0, 'test': 0}


In [3]:
sceneId = '000001'
sceneId1 = sceneId.lstrip('0')
sceneId = '0'




In [9]:
import numpy as np
x =np.random.random((5, 4, 3))
print(x)


[[[0.01101668 0.0538056  0.54948986]
  [0.36753204 0.856824   0.90061458]
  [0.52210387 0.9594439  0.49900022]
  [0.22027725 0.58160585 0.02137901]]

 [[0.98790452 0.56240437 0.66166439]
  [0.10817402 0.7164466  0.90158767]
  [0.84286698 0.50025549 0.57512687]
  [0.31119002 0.68692872 0.65454719]]

 [[0.59548461 0.84036008 0.57181481]
  [0.39229057 0.83146461 0.74253401]
  [0.75754687 0.98030659 0.04996127]
  [0.95778739 0.08104989 0.75572361]]

 [[0.46707657 0.37229431 0.37148522]
  [0.5272589  0.33826851 0.52310346]
  [0.50884484 0.18289252 0.36688074]
  [0.0195123  0.77846699 0.58876344]]

 [[0.39242239 0.27733288 0.83210092]
  [0.40088978 0.30076733 0.78988215]
  [0.68326848 0.19589243 0.72169646]
  [0.55587266 0.49053236 0.03217402]]]


In [10]:
x = x[:, :, ::-1]
print(x)



[[[0.54948986 0.0538056  0.01101668]
  [0.90061458 0.856824   0.36753204]
  [0.49900022 0.9594439  0.52210387]
  [0.02137901 0.58160585 0.22027725]]

 [[0.66166439 0.56240437 0.98790452]
  [0.90158767 0.7164466  0.10817402]
  [0.57512687 0.50025549 0.84286698]
  [0.65454719 0.68692872 0.31119002]]

 [[0.57181481 0.84036008 0.59548461]
  [0.74253401 0.83146461 0.39229057]
  [0.04996127 0.98030659 0.75754687]
  [0.75572361 0.08104989 0.95778739]]

 [[0.37148522 0.37229431 0.46707657]
  [0.52310346 0.33826851 0.5272589 ]
  [0.36688074 0.18289252 0.50884484]
  [0.58876344 0.77846699 0.0195123 ]]

 [[0.83210092 0.27733288 0.39242239]
  [0.78988215 0.30076733 0.40088978]
  [0.72169646 0.19589243 0.68326848]
  [0.03217402 0.49053236 0.55587266]]]
