In [4]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.12817054 0.0410761  0.52122677]
 [0.29734266 0.33333888 0.66704577]
 [0.16816688 0.40536611 0.93502101]
 [0.13216409 0.29510956 0.78811531]
 [0.98910434 0.28338254 0.84009348]
 [0.37888651 0.2834223  0.33012537]
 [0.29955708 0.00448454 0.33065588]
 [0.36078926 0.96835984 0.90020917]
 [0.04699901 0.19143186 0.19414983]
 [0.85509465 0.77067334 0.49011941]]


numpy.flatten()作用:
将多维度的数据展成1维

In [5]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 10],[11, 12, 13]])
print(a.shape)
b = a > 5 #
print(b)
c = b.flatten().nonzero()
print(c)
d = a.flatten()
print(d)
e = b.nonzero()
print(e)
# f = np.where(e[0] == 2)
# print(f)
row_list = e[0].tolist()
col_list = e[1].tolist()
row_fist_idx = row_list.index(3)  # 第一个等于3的值的索引
print(row_fist_idx)
# find_list = [2, 3]
# row_fist_idx_list = row_list.index(find_list)


(4, 3)
[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
(array([ 5,  6,  7,  8,  9, 10, 11]),)
[ 1  2  3  4  5  6  7  8 10 11 12 13]
(array([1, 2, 2, 2, 3, 3, 3]), array([2, 0, 1, 2, 0, 1, 2]))
4


In [6]:
e = a[c]
print(e)



IndexError: index 5 is out of bounds for axis 0 with size 4

In [ ]:
f = e[:, None]
print(f)



In [ ]:
f = e[:, np.newaxis]
print(f)

In [ ]:
f1 = a[:, np.newaxis]
print(f1)


In [ ]:
g = np.array([f])
print(g)


In [ ]:
c_mask = np.zeros(10)
c_mask[:5] = 1  # 将前五个数设置为1
np.random.shuffle(c_mask)
print(c_mask)


字典的相关用法

In [ ]:
student = [('name','xiao meng'), ('number','110')]
print(type(student))
dict_student = dict(student)    # cover list to dict
print(type(dict_student))



In [ ]:
idx = dict(
    tain = 0,
    val = 0,
    test = 0
)
print(idx)


In [ ]:
sceneId = '000001'
sceneId1 = sceneId.lstrip('0')
sceneId = '0'




In [ ]:
import numpy as np
np.random.seed(666)
x =np.random.random((4, 3))
print(x)
y = x[:,2:3]
print(y)


In [ ]:
x = x[:, :, ::-1]
print(x)



In [ ]:
a = [1, 2, 3]
print(len(a))




In [ ]:
a = "123.txt"
a = a[:-4]

In [ ]:
a = [1, 2]
if a :
    print(a)
else:
    print("d")



In [ ]:
a = np.array([0, 0, 1, 1, 1, 0])
b = a.nonzero()
print(len(b[0]))


数组中在一定范围内的数

In [7]:
min = 2
max = 10
np.random.seed(666)
a = np.random.randint(0, 15, 10)
print(a)
mask_min = a > min
mask_max = a < max
mask = mask_max & mask_min
choose = mask.nonzero()
in_range = a[choose]
print(in_range)





[12  2 13 14 14  6  9 14  4 13]
[6 9 4]


In [8]:
sub = [2, 6, 9]
c = np.where(a.tolist() == sub)
print(c)



(array([], dtype=int64),)


In [1]:
a = 5
b = 2
print(a//b)



2
