In [1]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.09366622 0.73203519 0.85648556]
 [0.89917467 0.34668802 0.00879755]
 [0.70443452 0.69765613 0.72248752]
 [0.71204872 0.55631818 0.69792112]
 [0.94559559 0.9834139  0.41590905]
 [0.44391017 0.51855196 0.43691681]
 [0.60207438 0.71575516 0.35595664]
 [0.94791822 0.32629689 0.4373158 ]
 [0.85902969 0.36413892 0.86524425]
 [0.53195522 0.20031795 0.16207422]]


numpy.flatten()作用:
将多维度的数据展成1维

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 10],[11, 12, 13]])
b = a > 5 #
print(b)
c = b.flatten().nonzero()
print(c)
d = a.flatten()
print(d)
e = b.nonzero()
print(e)
# f = np.where(e[0] == 2)
# print(f)
row_list = e[0].tolist()
col_list = e[1].tolist()
row_fist_idx = row_list.index(3)  # 第一个等于3的值的索引
print(row_fist_idx)


[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
(array([ 5,  6,  7,  8,  9, 10, 11]),)
[ 1  2  3  4  5  6  7  8 10 11 12 13]
(array([1, 2, 2, 2, 3, 3, 3]), array([2, 0, 1, 2, 0, 1, 2]))
4


In [4]:
e = a[c]
print(e)



IndexError: index 5 is out of bounds for axis 0 with size 4

In [4]:
f = e[:, None]
print(f)



[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [5]:
f = e[:, np.newaxis]
print(f)

[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [6]:
f1 = a[:, np.newaxis]
print(f1)


[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8 10]]

 [[11 12 13]]]


In [7]:
g = np.array([f])
print(g)


[[[ 6]
  [ 7]
  [ 8]
  [10]
  [11]
  [12]
  [13]]]


In [8]:
c_mask = np.zeros(10)
c_mask[:5] = 1  # 将前五个数设置为1
np.random.shuffle(c_mask)
print(c_mask)


[0. 1. 0. 1. 1. 0. 1. 0. 0. 1.]


字典的相关用法

In [9]:
student = [('name','xiao meng'), ('number','110')]
print(type(student))
dict_student = dict(student)    # cover list to dict
print(type(dict_student))



<class 'list'>
<class 'dict'>


In [10]:
idx = dict(
    tain = 0,
    val = 0,
    test = 0
)
print(idx)


{'tain': 0, 'val': 0, 'test': 0}


In [3]:
sceneId = '000001'
sceneId1 = sceneId.lstrip('0')
sceneId = '0'




In [8]:
import numpy as np
np.random.seed(666)
x =np.random.random((4, 3))
print(x)
y = x[:,2:3]
print(y)


[[0.70043712 0.84418664 0.67651434]
 [0.72785806 0.95145796 0.0127032 ]
 [0.4135877  0.04881279 0.09992856]
 [0.50806631 0.20024754 0.74415417]]
[[0.67651434]
 [0.0127032 ]
 [0.09992856]
 [0.74415417]]


In [10]:
x = x[:, :, ::-1]
print(x)



[[[0.54948986 0.0538056  0.01101668]
  [0.90061458 0.856824   0.36753204]
  [0.49900022 0.9594439  0.52210387]
  [0.02137901 0.58160585 0.22027725]]

 [[0.66166439 0.56240437 0.98790452]
  [0.90158767 0.7164466  0.10817402]
  [0.57512687 0.50025549 0.84286698]
  [0.65454719 0.68692872 0.31119002]]

 [[0.57181481 0.84036008 0.59548461]
  [0.74253401 0.83146461 0.39229057]
  [0.04996127 0.98030659 0.75754687]
  [0.75572361 0.08104989 0.95778739]]

 [[0.37148522 0.37229431 0.46707657]
  [0.52310346 0.33826851 0.5272589 ]
  [0.36688074 0.18289252 0.50884484]
  [0.58876344 0.77846699 0.0195123 ]]

 [[0.83210092 0.27733288 0.39242239]
  [0.78988215 0.30076733 0.40088978]
  [0.72169646 0.19589243 0.68326848]
  [0.03217402 0.49053236 0.55587266]]]


In [1]:
a = [1, 2, 3]
print(len(a))




3


In [3]:
a = "123.txt"
a = a[:-4]

In [15]:
a = [1, 2]
if a :
    print(a)
else:
    print("d")



[1, 2]
