In [1]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.20482336 0.73735482 0.24625922]
 [0.18330894 0.28810072 0.48512442]
 [0.53723862 0.26965417 0.70748936]
 [0.95016871 0.67247851 0.7261528 ]
 [0.59190444 0.65569144 0.72803323]
 [0.45949163 0.58959861 0.62355509]
 [0.50629482 0.03862034 0.94247055]
 [0.79979444 0.67415259 0.2293849 ]
 [0.20012023 0.76018489 0.76698917]
 [0.93256176 0.73331474 0.84005366]]


numpy.flatten()作用:
将多维度的数据展成1维

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 10],[11, 12, 13]])
print(a.shape)
b = a > 5 #
print(b)
c = b.flatten().nonzero()
print(c)
d = a.flatten()
print(d)
e = b.nonzero()
print(e)
# f = np.where(e[0] == 2)
# print(f)
row_list = e[0].tolist()
col_list = e[1].tolist()
row_fist_idx = row_list.index(3)  # 第一个等于3的值的索引
print(row_fist_idx)
# find_list = [2, 3]
# row_fist_idx_list = row_list.index(find_list)


(4, 3)
[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
(array([ 5,  6,  7,  8,  9, 10, 11]),)
[ 1  2  3  4  5  6  7  8 10 11 12 13]
(array([1, 2, 2, 2, 3, 3, 3]), array([2, 0, 1, 2, 0, 1, 2]))
4


In [3]:
e = a[c]
print(e)



IndexError: index 5 is out of bounds for axis 0 with size 4

In [ ]:
f = e[:, None]
print(f)



In [ ]:
f = e[:, np.newaxis]
print(f)

In [ ]:
f1 = a[:, np.newaxis]
print(f1)


In [ ]:
g = np.array([f])
print(g)


In [ ]:
c_mask = np.zeros(10)
c_mask[:5] = 1  # 将前五个数设置为1
np.random.shuffle(c_mask)
print(c_mask)


字典的相关用法

In [ ]:
student = [('name','xiao meng'), ('number','110')]
print(type(student))
dict_student = dict(student)    # cover list to dict
print(type(dict_student))



In [ ]:
idx = dict(
    tain = 0,
    val = 0,
    test = 0
)
print(idx)


In [ ]:
sceneId = '000001'
sceneId1 = sceneId.lstrip('0')
sceneId = '0'




In [ ]:
import numpy as np
np.random.seed(666)
x =np.random.random((4, 3))
print(x)
y = x[:,2:3]
print(y)


In [ ]:
x = x[:, :, ::-1]
print(x)



In [ ]:
a = [1, 2, 3]
print(len(a))




In [ ]:
a = "123.txt"
a = a[:-4]

In [ ]:
a = [1, 2]
if a :
    print(a)
else:
    print("d")



In [ ]:
a = np.array([0, 0, 1, 1, 1, 0])
b = a.nonzero()
print(len(b[0]))


数组中在一定范围内的数

In [ ]:
min = 2
max = 10
np.random.seed(666)
a = np.random.randint(0, 15, 10)
print(a)
mask_min = a > min
mask_max = a < max
mask = mask_max & mask_min
choose = mask.nonzero()
in_range = a[choose]
print(in_range)





In [ ]:
sub = 2
c = np.where(a.tolist() == sub)
print(c)



In [ ]:
a = 5
b = 2
print(a//b)



字符串拼接

In [ ]:
a = 0.0345678
epoch = 2
name = '_%.4f'% a + "ep{}".format(epoch)
print(name)


查找 list 中等于指定的值

In [ ]:
a = [0, 0 , 2, 4, 1, 1]
b = a == 1
print(b)



In [ ]:
a = np.array([0, 1, 0, 1, 1, 1, 0, 0])
b = np.array([0, 0, 1, 0, 1, 1, 1, 0])
c = a & b
print(c)
d = a - c
print(d)
e = b - a
e = e > 0
e = e.nonzero()

print(e)
f = np.append(a, b)
print(f)


list 转 array

In [4]:
a = [0, 1, 0, 2, 3, 0, 0, 5]
b = np.asarray(a).mean()
print(b)




1.375


In [5]:
a = True
b = False
if a & (not b):
    print("1")
    


1


二值label转class label

In [6]:
a = np.array([0, 0, 1, 0, 1])
b = np.array([0, 1, 0, 0, 0])
c = a & b
d = a - b
print(d)
a_idx = d > 0
b_idx = d < 0
print(a_idx)
print(a_idx.size)
a_nozero = a_idx.nonzero()[0]
print(a_nozero)
print(a_nozero.size)
print(type(a_nozero))
label = np.zeros(5)
label[a_idx] = 1
label[b_idx] = 2
print(label)

a_label_idx = np.where(label == 1)


[ 0 -1  1  0  1]
[False False  True False  True]
5
[2 4]
2
<class 'numpy.ndarray'>
[0. 2. 1. 0. 1.]


In [7]:
suction_mask = np.zeros((502,671)).astype("uint8")

In [8]:
s = "1234567"
s_1 = s[-2:]
print(s_1)

67


In [21]:
a = np.array([1.1, 1.3, 1.3, 1.2, 1.3, 1.3, 1.2])
b = np.array([1, 2, 2, 3])
n, idx = np.unique(a, return_index=True)
_, inverse = np.unique(a, return_inverse=True)
print(n)
print(idx)
print(inverse)

# mask = inverse == 1
# mask_sum = np.sum(mask)

for i in n:
    mask = a == i
    num_n = np.sum(mask)
    print(np.sum(mask))
    if num_n > 1:
        print("{}:{}".format(i, mask))

[1.1 1.2 1.3]
[0 3 1]
[0 2 2 1 2 2 1]
1
2
1.2:[False False False  True False False  True]
4
1.3:[False  True  True False  True  True False]
