In [14]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.08973674 0.45896483 0.08736129]
 [0.7615993  0.27417811 0.5036609 ]
 [0.62488502 0.85312913 0.43556164]
 [0.98086759 0.42820961 0.93945909]
 [0.57284162 0.9690916  0.91524483]
 [0.94262496 0.74273448 0.37886115]
 [0.64549685 0.09030538 0.03016169]
 [0.86080483 0.37194447 0.62937412]
 [0.02782052 0.28427647 0.84077243]
 [0.43758898 0.43500352 0.34533688]]


numpy.flatten()作用:

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 10],[11, 12, 13]])
b = a > 5 #
print(b)
c = b.flatten().nonzero()[0]
print(c)
d = a.flatten()
print(d)



[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]
[ 5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8 10 11 12 13]


In [16]:
e = a.flatten()[c]
print(e)



[ 6  7  8 10 11 12 13]


In [17]:
f = e[:, None]
print(f)



[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [18]:
f = e[:, np.newaxis]
print(f)

[[ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]
 [13]]


In [19]:
f1 = a[:, np.newaxis]
print(f1)


[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8 10]]

 [[11 12 13]]]


In [21]:
g = np.array([f])
print(g)


[[[ 6]
  [ 7]
  [ 8]
  [10]
  [11]
  [12]
  [13]]]


In [23]:
c_mask = np.zeros(10)
c_mask[:5] = 1  # 将前五个数设置为1
np.random.shuffle(c_mask)
print(c_mask)


[1. 0. 1. 0. 0. 0. 0. 1. 1. 1.]
