In [3]:
import numpy as np
normal = np.random.random((10,3))
print(normal)

[[0.60026415 0.2676508  0.63300925]
 [0.46935436 0.66764286 0.9692209 ]
 [0.77085518 0.25122843 0.61154902]
 [0.22468885 0.82946159 0.51153034]
 [0.86640889 0.09781712 0.74908847]
 [0.4369943  0.46324704 0.34509958]
 [0.83892961 0.63695474 0.14389116]
 [0.88471942 0.81723368 0.04864139]
 [0.77082892 0.58280764 0.82191027]
 [0.70335632 0.61563859 0.20602683]]
