In [19]:
import torch
torch.manual_seed(0)

**创建Tensor**

In [20]:
x = torch.tensor([1., 2., 3.])
print(x)

tensor([1., 2., 3.])


**索引**

与numpy类似<br/>
索引出来的结果与原数据共享内存，即修改一个，另一个会跟着修改。

In [21]:
y = x[1]
print(y)
y += 1
print(y)
print(x)

tensor(2.)
tensor(3.)
tensor([1., 3., 3.])


**复制** <br/>
tensor.clone():开辟新的内存,但任然保留在计算图中<br/>
tensor.detach():共享内存,不保留在计算图中<br/>
tensor.clone().detach():开辟新的内存,不保留在计算图中

In [22]:
y = x[1].clone().detach()
print(y)
print(x[1])

tensor(3.)
tensor(3.)


In [23]:
y = 4
print(x[1])

tensor(3.)


**改变形状** view()<br/>
view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的，也即更改其中的一个，另外一个也会跟着改变。<br/>
所以如果我们想返回一个真正新的副本（即不共享data内存）,可以先clone().detach(),然后view()

In [25]:
x = torch.rand(5,3)
y = x.view(15)
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())


torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**将Tensor标量转换为Python number** item()

In [26]:
x = torch.randn(1)
print(x)
print(x.item())




tensor([0.6035])
0.6035430431365967


## 广播机制 ##
当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算。

In [27]:
x = torch.arange(1, 3)
y = torch.arange(1, 4)
print(x)
print(y)


tensor([1, 2])
tensor([1, 2, 3])


In [29]:
y = y.view(3, 1)
print(y)


tensor([[1],
        [2],
        [3]])


In [30]:
print(x + y)

tensor([[2, 3],
        [3, 4],
        [4, 5]])


## Tensor和NumPy相互转换 ##

**Tensor转NumPy** numpy()

共享相同的内存,其中一个改变,另一个也会改变

In [31]:
a = torch.ones(5)
b = a.numpy()
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)




tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


**Numpy转Tensor** from_numpy()

共享内存

In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)



[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


**Numpy转Tensor** torch.tensor()
开辟新的空间,不再共享内存

In [34]:
c = torch.tensor(a)
c += 1
print(a, c)




[3. 3. 3. 3. 3.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)


##Tensor on GPU##
to()

In [37]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)   # 直接创建一个在GPU上的Tensor
    z = x.clone().detach()
    x = x.to(device)        # 等价于 .to("cuda")
    z = z.to("cuda")
    l =x + y + z
    print(l)
    print(l.to("cpu"))







tensor([3, 5], device='cuda:0')
tensor([3, 5])
