In [8]:
import torch

a = torch.tensor([[[1,0],[1,0],[0, 1],[0, 1]]])
print(a.size())

torch.Size([1, 4, 2])


In [9]:
b, c = torch.max(a, 2)

In [11]:
d = torch.tensor([[[1,0,2],[1,0,0],[0, 1,3]]])
_, e = torch.max(d, -1)

In [14]:
print(e)
print(e.size())
print(e[0])
print(e[0].size())


tensor([[2, 0, 2]])
torch.Size([1, 3])
tensor([2, 0, 2])
torch.Size([3])


In [17]:
mask = c[0] == 1
f = a[:, mask, :]
print(f)

tensor([[[0, 1],
         [0, 1]]])


In [19]:
g = f[0].numpy()