pip install transforms3d

matrix to euler and euler to matrix

In [1]:
import transforms3d as t3d

# compose transform matrix
T = [20, 30, 40]
R = [[0, -1, 0], [1, 0, 0], [0, 0, 1]] # rotation matrix
Z = [2.0, 3.0, 4.0] # zooms
A = t3d.affines.compose(T, R, Z)
print(A)






[[ 0. -3.  0. 20.]
 [ 2.  0.  0. 30.]
 [ 0.  0.  4. 40.]
 [ 0.  0.  0.  1.]]


In [2]:
#transform matrix to euler
Z1 = [1, 1, 1]
B = t3d.affines.compose(T, R, Z1)
print(B)
rx, ry, rz = t3d.euler.mat2euler(R, axes='sxyz')
print(rx, ry ,rz)



[[ 0. -1.  0. 20.]
 [ 1.  0.  0. 30.]
 [ 0.  0.  1. 40.]
 [ 0.  0.  0.  1.]]
0.0 -0.0 1.5707963267948966


In [3]:
# transform euler to matrix
R1 = t3d.euler.euler2mat(rx, ry, rz, axes='sxyz')
print(R1.astype(float))


[[ 6.123234e-17 -1.000000e+00  0.000000e+00]
 [ 1.000000e+00  6.123234e-17 -0.000000e+00]
 [ 0.000000e+00  0.000000e+00  1.000000e+00]]


show axes

In [4]:
import open3d as o3d
import math
import numpy as np
base_coordinate = o3d.create_mesh_coordinate_frame(size=1000)
coordinate1 = o3d.create_mesh_coordinate_frame(size=500)
coordinate2 = o3d.create_mesh_coordinate_frame(size=300)
r_xyz = np.array([180.272, 9.67795, 270.592]) # camera in base pose
r_xyz = r_xyz/180*math.pi
R_1 = t3d.euler.euler2mat(r_xyz[0], r_xyz[1], r_xyz[2], axes='sxyz')
T_1 = np.array([0.3931, -0.280894, 1.33803])*1000
H_1 = t3d.affines.compose(T_1, R_1, Z1)
print(H_1)
coordinate1.transform(H_1)
# o3d.visualization.draw_geometries([coordinate1, base_coordiate])

R_2in1 = np.array([[0, -1, 0],
          [-1, 0, 0],
          [0, 0, -1]])
R_2 = R_1.dot(R_2in1)
H_2 = t3d.affines.compose(T_1, R_2, Z1)
coordinate2.transform(H_2)
o3d.visualization.draw_geometries([coordinate1, base_coordinate, coordinate2])
rx_2, ry_2, rz_2 = t3d.euler.mat2euler(R_2, axes='sxyz')
print(rx_2, ry_2, rz_2)

[[ 1.01851204e-02 -9.99943600e-01  3.01010334e-03  3.93100000e+02]
 [-9.85715620e-01 -9.53402653e-03  1.68148206e-01 -2.80894000e+02]
 [-1.68110024e-01 -4.67971561e-03 -9.85757130e-01  1.33803000e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
0.16891395973291096 -0.004679732689949227 0.009534275374698208
